---
- name: Get facts
  hosts: all
  connection: local
  gather_facts: no
  vars:

  tasks:
    - name: get facts from device
      napalm_get_facts:
        hostname: "{{ host }}"
        username: "{{ user }}"
        dev_os: "{{ os }}"
        password: "{{ password }}"
        optional_args:
          port: "{{ port }}"
        filter: ['bgp_neighbors']
      register: napalm_facts
    - name: Check BGP sessions are healthy
      assert:
        that:
          - napalm_facts.ansible_facts.bgp_neighbors.global.peers[hostvars[item.value.attributes.connects_to_device]['interfaces'][item.value.attributes.connects_to_iface]['ipv6'][0].split('/')[0]].is_up
        msg: "{{ hostvars[item.value.attributes.connects_to_device]['interfaces'][item.value.attributes.connects_to_iface]['ipv6'][0].split('/')[0] }} is down" 
      with_dict: "{{ interfaces }}"
      when: "{{ item.value.attributes.link_type == 'fabric' }}"
      tags: [print_action]
    - name: Chack BGP sessions are receiving prefixes
      assert:
        that:
          - napalm_facts.ansible_facts.bgp_neighbors.global.peers[hostvars[item.value.attributes.connects_to_device]['interfaces'][item.value.attributes.connects_to_iface]['ipv6'][0].split('/')[0]].address_family.ipv6.received_prefixes > 0
        msg: "{{ hostvars[item.value.attributes.connects_to_device]['interfaces'][item.value.attributes.connects_to_iface]['ipv6'][0].split('/')[0] }} is not receiving any prefixes"
      with_dict: "{{ interfaces }}"
      when: "{{ item.value.attributes.link_type == 'fabric' }}"
      tags: [print_action]
